config/routes.rb
Rails.application.routes.draw do
  root to: 'property#index'
  
  get '/properties', to: 'property#index', as: 'properties'
  get '/property/:id', to: 'property#show', as: 'property'

  get '/users', to: 'user#index', as: 'users'
  get '/user/:id', to: 'user#show', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :user_property_scores
  has_many :users, through: :user_property_scores
  
  has_many :availabilities
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_property_scores
  has_many :properties, through: :user_property_scores
end

app/models/user_property_score.rb
class UserPropertyScore < ApplicationRecord
  validates :score, presence: true
  
  belongs_to :user
  belongs_to :property
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/property_controller.rb
class PropertyController < ApplicationController
  def index
    @page = params["page"].blank? ? 1 : params["page"].to_i
    limit = 25
    offset = (@page - 1) * limit
    @max_page = (Property.count.to_f / limit.to_f).ceil

    @properties = Property
                    .order(name: :asc)
                    .limit(limit)
                    .offset(offset)
  end

  def show
    @property = Property.find(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  include Geocoder::Calculations

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @properties = get_interest_base_properties
    @nearby_properties = get_nearby_properties
  end

  private

  def get_nearby_properties
    latitude, longitude = user_coordinates_from_geocoder

    latitude && longitude && find_nearby_properties(latitude, longitude, Constants::DISTANCE_IN_MILES) || []
  end

  def user_coordinates_from_geocoder
    city_cordinates = Geocoder.search(@user.city)
    state_cordinates = Geocoder.search(@user.state) if city_cordinates.empty?
    cordinates =  state_cordinates || city_cordinates

    latitude = cordinates.first.data["lat"]
    longitude = cordinates.first.data["lon"]

    [latitude, longitude]
  end

  def find_nearby_properties(latitude, longitude, max_distance_miles)
    user_coordinates = [latitude, longitude]

    nearby_properties = Property.all.map do |property|
      property_coordinates = [property.lat, property.lng]
      distance_miles = distance_between(user_coordinates, property_coordinates) * 0.621371

      { property:, distance_miles: }
    end

    sorted_properties = nearby_properties
      .select { |prop| prop[:distance_miles] <= max_distance_miles }
      .sort_by { |prop| prop[:distance_miles] }
      .first(3)

    sorted_properties.map { |prop| prop[:property] }
  end

  def get_interest_base_properties
    Property.joins(:user_property_scores)
           .where(user_property_scores: { user_id: @user.id })
           .order('user_property_scores.score DESC')
           .first(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/property_helper.rb
module PropertyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thirdhoem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/property/_amenities.html.erb
<% if amenities.is_a? Enumerable %>
  <% amenities.each do |amenity| %>
    <li class="list-group-item">
      <% arr_amenity = amenity.split(":") %>
      <% if arr_amenity.second == "true" || arr_amenity.second == "false" %>
        <%= arr_amenity.first.humanize(capitalize: true) %>
      <% else %>
        <%= arr_amenity.second %>
      <% end %>
    </li>
  <% end %>
<% end %>

app/views/property/_availability.html.erb
<div class="row">
  <div class="col-md-4 py-2">
    <%= availability.starts_on.strftime("%b %d, %Y") %> - <%= availability.ends_on.strftime("%b %d, %Y") %>
  </div>
  <div class="col-md-4 py-2">
    <strong>Rate:</strong> <%= number_to_currency(availability.reserve_price) %>
  </div>
  <div class="col-md-4 py-2">
    <button type="button" class="btn btn-primary">Book</button>
  </div>
</div>

app/views/property/index.html.erb
<div class="container mt-5">
  <%= link_to 'See Users'.html_safe, users_path, class: 'btn btn-success float-end' %>
  <h1 class="mb-4">All Properties</h1>

  <ul class="list-group">
    <% @properties.each do |property| %>
      <li class="list-group-item">
        <%= link_to property.name, property_path(property), class: 'text-decoration-none' %>
      </li>
    <% end %>
  </ul>

  <nav aria-label="Properties Pagination" class="mt-4">
    <ul class="pagination justify-content-center">
      <% unless @page == 1 %>
        <li class="page-item">
          <%= link_to '&laquo; Previous'.html_safe, properties_path(page: @page - 1), class: 'page-link' %>
        </li>
      <% else %>
        <li class="page-item disabled">
          <span class="page-link">&laquo; Previous</span>
        </li>
      <% end %>

      <% unless @page == @max_page %>
        <li class="page-item">
          <%= link_to 'Next &raquo;'.html_safe, properties_path(page: @page + 1), class: 'page-link' %>
        </li>
      <% else %>
        <li class="page-item disabled">
          <span class="page-link">Next &raquo;</span>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/property/show.html.erb
<%= link_to 'Back to Users'.html_safe, users_path, class: 'btn btn-success float-end' %>
<%= link_to 'Back to Properties'.html_safe, properties_path, class: 'btn btn-success' %>

<h1 class="text-center">Property Details</h1>

<div class="row">
  <div class="col-md-12 text-center mb-3 mt-3P">
    <h4><%= @property.name %></h4>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <%= image_tag @property.primary_photo_url, width: 600, class: "rounded" %>
  </div>
  <div class="col-md-6">
    <p><%= @property.description %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2 py-2">
    <strong>City:</strong>
  </div>
  <div class="col-md-10 py-2 py-2">
    <%= @property.city %>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>State:</strong>
  </div>
  <div class="col-md-10 py-2">
    <%= @property.state %>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>Country:</strong>
  </div>
  <div class="col-md-10 py-2">
    <%= @property.country_code %>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>Location:</strong>
  </div>
  <div class="col-md-10 py-2">
    (<%= @property.lat %>, <%= @property.lng %>)
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>Property Style:</strong>
  </div>
  <div class="col-md-10 py-2">
    <%= @property.property_style %>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>Property Type:</strong>
  </div>
  <div class="col-md-10 py-2">
    <%= @property.property_type %>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>Max Occupancy:</strong>
  </div>
  <div class="col-md-10 py-2">
    <%= @property.max_occupancy %>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>Bedrooms:</strong>
  </div>
  <div class="col-md-10 py-2">
    <%= @property.bedrooms_count %>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>Square Footage:</strong>
  </div>
  <div class="col-md-10 py-2">
    <%= @property.square_feet %>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>View from Property:</strong>
  </div>
  <div class="col-md-10 py-2">
    <%= @property.view_from_property %>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>Airport:</strong>
  </div>
  <div class="col-md-10 py-2">
    <%= @property.distance_from_airtport %> from <%= @property.nearest_airport %>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>Amenities:</strong>
  </div>
  <div class="col-md-10 py-2">
    <ul class="list-group">
      <%= render partial: 'amenities', locals: { amenities: @property['amenities'] } %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>Activities:</strong>
  </div>
  <div class="col-md-10 py-2">
    <ul class="list-group">
    <% if @property.activities.is_a? Enumerable %>
      <% @property.activities.each do |activity, available| %>
        <% if available %>
          <li class="list-group-item"><%= activity.titleize %></li>
        <% end %>
      <% end %>
    <% end %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>Places of Interest:</strong>
  </div>
  <div class="col-md-10 py-2">
    <ul class="list-group">
      <% if @property.interest_places.is_a? Enumerable %>
        <% @property.interest_places.each do |place| %>
          <li class="list-group-item"><%= place %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-2 py-2">
    <strong>Activities of Interest:</strong>
  </div>
  <div class="col-md-10 py-2">
    <ul class="list-group">
      <% if @property.interest_activities.is_a? Enumerable %>
        <% @property.interest_activities.each do |activity| %>
          <li class="list-group-item"><%= activity %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>Availabilities</h2>
    <% @property.availabilities.uniq{ |a| [a.starts_on, a.ends_on]}.each do |availability| %>
      <%= render partial: 'availability', locals: { availability: availability } %>
    <% end %>
  </div>
</div>

app/views/user/index.html.erb
<div class="container mt-5">
  <%= link_to 'Back to Properties', properties_path, class: 'btn btn-success float-end' %>
  <h1 class="mb-4">All Users</h1>

  <ul class="list-group">
    <% @users.each do |user| %>
      <li class="list-group-item">
        <%= link_to user.name, user, class: 'text-decoration-none' %>
      </li>
    <% end %>
  </ul>
</div>

app/views/user/show.html.erb
<div class="container mt-5">
  <%= link_to 'Back to Users', users_path, class: 'btn btn-success float-end mb-3' %>
  <%= link_to 'Back to Properties', properties_path, class: 'btn btn-success mb-3' %>

  <h1 class="text-center mb-4">User Details</h1>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>Name:</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>Email:</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>Location:</th>
        <td><%= "#{@user.city}, #{@user.state} #{@user.country_code}" %></td>
      </tr>
      <tr>
        <th>Interests:</th>
        <td><%= @user.interests.join(", ") %></td>
      </tr>
      <tr>
        <th>Properties:</th>
        <td>
          <% @properties.each do |property| %>
            <div class="row mb-4">
              <div class="col-md-3">
                <%= image_tag property.primary_photo_url, class: "img-thumbnail" %>
              </div>
              <div class="col-md-9">
                <h4><%= link_to property.name, property_path(property), class: 'text-decoration-none' %></h4>
                <p><%= property.description.truncate(300) %></p>
                <% score = number_to_percentage(property.user_property_scores.find_by(user_id: @user.id).score * 100, precision: 0) %>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: <%= score %>" aria-valuenow="<%= score %>" aria-valuemin="0" aria-valuemax="100"><%= score %> match</div>
                </div>
              </div>
            </div>
            <hr class="mb-4">
          <% end %>
        </td>
      </tr>

      <tr>
        <th>Nearby Properties:</th>
        <td>
          <% if @nearby_properties.empty? %>
            <p>There are no nearby properties within a 50-mile range</p>
          <% else %>
            <% @nearby_properties.each do |property| %>
              <div class="row mb-4">
                <div class="col-md-3">
                  <%= image_tag property.primary_photo_url, class: "img-thumbnail" %>
                </div>
                <div class="col-md-9">
                  <h4><%= link_to property.name, property_path(property), class: 'text-decoration-none' %></h4>
                  <p><%= property.description.truncate(300) %></p>
                </div>
              </div>
              <hr class="mb-4">
            <% end %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>